# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 15:25
from __future__ import unicode_literals

import contactboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    replaces = [('contactboard', '0001_initial'), ('contactboard', '0002_change_meta'), ('contactboard', '0003_split_compartir'), ('contactboard', '0004_nom_cognoms_pare_mare'), ('contactboard', '0005_data_de_naixement_opcional'), ('contactboard', '0006_nom_i_cognoms_unics'), ('contactboard', '0007_disabled_data_de_naixement')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('cognoms', models.CharField(max_length=255)),
                ('data_de_naixement', models.DateField(blank=True, editable=False, null=True)),
                ('nom_pare', models.CharField(blank=True, max_length=255, verbose_name='nom del pare')),
                ('cognoms_pare', models.CharField(blank=True, max_length=255, verbose_name='cognoms del pare')),
                ('nom_mare', models.CharField(blank=True, max_length=255, verbose_name='nom de la mare')),
                ('cognoms_mare', models.CharField(blank=True, max_length=255, verbose_name='cognoms de la mare')),
                ('correu_alumne', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name="correu de l'alumne")),
                ('compartir_correu_alumne', models.BooleanField(default=False, verbose_name="compartir correu de l'alumne")),
                ('correu_pare', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='correu del pare')),
                ('compartir_correu_pare', models.BooleanField(default=False, verbose_name='compartir correu del pare')),
                ('correu_mare', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='correu de la mare')),
                ('compartir_correu_mare', models.BooleanField(default=False, verbose_name='compartir correu de la mare')),
                ('telefon_alumne', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ^\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    $\n    ', 96))], verbose_name="telèfon de l'alumne")),
                ('compartir_telefon_alumne', models.BooleanField(default=False, verbose_name="compartir telèfon de l'alumne")),
                ('telefon_pare', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ^\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    $\n    ', 96))], verbose_name='telèfon del pare')),
                ('compartir_telefon_pare', models.BooleanField(default=False, verbose_name='compartir telèfon del pare')),
                ('telefon_mare', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ^\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    $\n    ', 96))], verbose_name='telèfon de la mare')),
                ('compartir_telefon_mare', models.BooleanField(default=False, verbose_name='compartir telèfon de la mare')),
            ],
            options={
                'ordering': ['cognoms', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('id_interna', models.SlugField(max_length=20, primary_key=True, serialize=False, validators=[contactboard.models.validate_non_reserved_id])),
            ],
            options={
                'ordering': ['curs', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('id_interna', models.SlugField(max_length=20, primary_key=True, serialize=False)),
                ('ordre', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'cursos',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='curs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='contactboard.Curs'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactboard.Classe'),
        ),
        migrations.AlterUniqueTogether(
            name='alumne',
            unique_together=set([('nom', 'cognoms')]),
        ),
    ]
