# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:21
from __future__ import unicode_literals

import contactboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('cognoms', models.CharField(max_length=255)),
                ('data_de_naixement', models.DateField()),
                ('correu_alumne', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('correu_pare', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('correu_mare', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefon_pare', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    ', 96))], verbose_name='telèfon pare')),
                ('telefon_mare', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    ', 96))], verbose_name='telèfon mare')),
                ('compartir', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('id_interna', models.SlugField(max_length=20, primary_key=True, serialize=False, validators=[contactboard.models.validate_non_reserved_id])),
            ],
        ),
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('id_interna', models.SlugField(max_length=20, primary_key=True, serialize=False)),
                ('ordre', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='curs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='contactboard.Curs'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactboard.Classe'),
        ),
    ]
