# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contactboard', '0001_squashed_0007_v1_0_0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumne',
            old_name='cognoms_mare',
            new_name='cognoms_tutor_2',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='cognoms_pare',
            new_name='cognoms_tutor_1',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='compartir_correu_mare',
            new_name='compartir_correu_tutor_2',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='compartir_correu_pare',
            new_name='compartir_correu_tutor_1',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='compartir_telefon_mare',
            new_name='compartir_telefon_tutor_2',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='compartir_telefon_pare',
            new_name='compartir_telefon_tutor_1',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='correu_mare',
            new_name='correu_tutor_2',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='correu_pare',
            new_name='correu_tutor_1',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='nom_mare',
            new_name='nom_tutor_2',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='nom_pare',
            new_name='nom_tutor_1',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='telefon_mare',
            new_name='telefon_tutor_2',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='telefon_pare',
            new_name='telefon_tutor_1',
        ),
        migrations.AlterField(
            model_name='alumne',
            name='cognoms_tutor_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='cognoms del tutor 1'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='cognoms_tutor_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='cognoms del tutor 2'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='compartir_correu_tutor_1',
            field=models.BooleanField(default=False, verbose_name='compartir correu del tutor 1'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='compartir_correu_tutor_2',
            field=models.BooleanField(default=False, verbose_name='compartir correu del tutor 2'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='compartir_telefon_tutor_1',
            field=models.BooleanField(default=False, verbose_name='compartir telèfon del tutor 1'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='compartir_telefon_tutor_2',
            field=models.BooleanField(default=False, verbose_name='compartir telèfon del tutor 2'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='correu_tutor_1',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='correu del tutor 1'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='correu_tutor_2',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='correu del tutor 2'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='nom_tutor_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom del tutor 1'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='nom_tutor_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom del tutor 2'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='telefon_tutor_1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ^\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    $\n    ', 96))], verbose_name='telèfon del tutor 1'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='telefon_tutor_2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ^\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    $\n    ', 96))], verbose_name='telèfon del tutor 2'),
        ),
    ]
