# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactboard', '0001_squashed_0007_v1_0_0'),
    ]

    operations = [
        # Migració buida per a facilitar el "merge" amb la branca
        # "mare"/"pare" => "tutor"
    ]
