# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 22:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contactboard', '0002_change_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumne',
            name='compartir',
        ),
        migrations.AddField(
            model_name='alumne',
            name='compartir_correu_alumne',
            field=models.BooleanField(default=False, verbose_name="compartir correu de l'alumne"),
        ),
        migrations.AddField(
            model_name='alumne',
            name='compartir_correu_mare',
            field=models.BooleanField(default=False, verbose_name='compartir correu de la mare'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='compartir_correu_pare',
            field=models.BooleanField(default=False, verbose_name='compartir correu del pare'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='compartir_telefon_alumne',
            field=models.BooleanField(default=False, verbose_name="compartir telèfon de l'alumne"),
        ),
        migrations.AddField(
            model_name='alumne',
            name='compartir_telefon_mare',
            field=models.BooleanField(default=False, verbose_name='compartir telèfon de la mare'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='compartir_telefon_pare',
            field=models.BooleanField(default=False, verbose_name='compartir telèfon del pare'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='telefon_alumne',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    ', 96))], verbose_name="telèfon de l'alumne"),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='correu_alumne',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name="correu de l'alumne"),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='correu_mare',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='correu de la mare'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='correu_pare',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='correu del pare'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='telefon_mare',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    ', 96))], verbose_name='telèfon de la mare'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='telefon_pare',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('\n    ((\\+|00)34)?  # Accepta prefixos (+34/0034)\n    [679][0-9]{8}\n    ', 96))], verbose_name='telèfon del pare'),
        ),
    ]
