# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactboard', '0002_noop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumne',
            name='data_de_naixement',
        ),
    ]
