# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactboard', '0004_nom_cognoms_pare_mare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='data_de_naixement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
