# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactboard', '0005_data_de_naixement_opcional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alumne',
            unique_together=set([('nom', 'cognoms')]),
        ),
    ]
