# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactboard', '0006_nom_i_cognoms_unics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='data_de_naixement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
