# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IesImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifile', models.FileField(upload_to='import', verbose_name="Arxiu d'importació")),
                ('class_dict', models.TextField(default='{}', help_text='Un text en format JSON que descriu com associar les classes de l\'arxiu a les classes de la base de dades. Una entrada amb \'null\' eliminarà la classe: {"<pk classe>": [<nom a l\'arxiu>, ...] | null, ...}\' Ex. \'{"1": ["1 ESO A"], "2": null}', verbose_name='Mapa de classes')),
                ('delete_other', models.BooleanField(default=True, help_text='Esborra els alumnes no mencionats de la base de dades', verbose_name='Eliminar no mencionats')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Última modificació')),
            ],
        ),
    ]
