# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importexport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iesimport',
            name='ifile',
            field=models.FileField(upload_to='uploads/import', verbose_name="Arxiu d'importació"),
        ),
    ]
