# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-10 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contactboard', '0003_remove_alumne_data_de_naixement'),
        ('importexport', '0002_canviat_desti_importacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAlumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_classe', models.CharField(max_length=20)),
                ('classe_mapejada', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactboard.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='DeleteAlumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminacions', to='contactboard.Alumne')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeleteClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminacions', to='contactboard.Classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('cognoms', models.CharField(max_length=255)),
                ('codi_classe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MoveAlumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvis_classe', to='contactboard.Alumne')),
                ('dada_relacionada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvi_movealumne', to='importexport.ImportData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='iesimport',
            old_name='last_mod',
            new_name='ultima_mod',
        ),
        migrations.RemoveField(
            model_name='iesimport',
            name='class_dict',
        ),
        migrations.RemoveField(
            model_name='iesimport',
            name='delete_other',
        ),
        migrations.RemoveField(
            model_name='iesimport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='iesimport',
            name='ifile',
        ),
        migrations.AddField(
            model_name='iesimport',
            name='canvis_calculats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iesimport',
            name='eliminar_classes_buides',
            field=models.BooleanField(default=True, help_text='Esborra les classes que quedin buides'),
        ),
        migrations.AddField(
            model_name='iesimport',
            name='id_importacio',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='iesimport',
            name='nom_importacio',
            field=models.CharField(default='<Sense nom>', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movealumne',
            name='importacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvis_movealumne', to='importexport.IesImport'),
        ),
        migrations.AddField(
            model_name='movealumne',
            name='nova_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnes_moguts_a', to='contactboard.Classe'),
        ),
        migrations.AddField(
            model_name='importdata',
            name='importacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dades_relacionades', to='importexport.IesImport'),
        ),
        migrations.AddField(
            model_name='deleteclasse',
            name='importacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvis_deleteclasse', to='importexport.IesImport'),
        ),
        migrations.AddField(
            model_name='deletealumne',
            name='importacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvis_deletealumne', to='importexport.IesImport'),
        ),
        migrations.AddField(
            model_name='classmap',
            name='importacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importexport.IesImport'),
        ),
        migrations.AddField(
            model_name='addalumne',
            name='dada_relacionada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvi_addalumne', to='importexport.ImportData'),
        ),
        migrations.AddField(
            model_name='addalumne',
            name='importacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvis_addalumne', to='importexport.IesImport'),
        ),
        migrations.AddField(
            model_name='addalumne',
            name='nova_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnes_nous', to='contactboard.Classe'),
        ),
        migrations.AlterUniqueTogether(
            name='importdata',
            unique_together=set([('importacio', 'nom', 'cognoms')]),
        ),
        migrations.AlterUniqueTogether(
            name='classmap',
            unique_together=set([('importacio', 'codi_classe')]),
        ),
    ]
