# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-07 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def calc_alumne(apps, schema_editor):
    from django.db.models import OuterRef, Subquery

    ImportData = apps.get_model('importexport', 'ImportData')
    Alumne = apps.get_model('contactboard', 'Alumne')
    ImportData.objects.update(alumne=Subquery(
        Alumne.objects.filter(
            nom=OuterRef('nom'), cognoms=OuterRef('cognoms'))
        .order_by().values('pk')))


class Migration(migrations.Migration):

    dependencies = [
        ('contactboard', '0003_remove_alumne_data_de_naixement'),
        ('importexport', '0003_iesformat_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdata',
            name='alumne',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='contactboard.Alumne'),
        ),
        migrations.RunPython(
            calc_alumne, reverse_code=migrations.RunPython.noop,
            elidable=True),
    ]
