# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usermanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contactboard.Alumne')),
            ],
        ),
        migrations.CreateModel(
            name='UnregisteredUser',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$'), usermanager.models.validate_username_unique], verbose_name="Nom d'usuari")),
                ('codi', models.CharField(help_text="Un codi numèric de 6 dígits per confirmar que l'usuari pertany a aquesta persona. Si no s'entra cap, es generarà un automàticament", max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$')])),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='unregisteredUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanager.UnregisteredUser', verbose_name='Usuari (sense registrar)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuari'),
        ),
    ]
