# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'perfil'},
        ),
        migrations.AlterModelOptions(
            name='unregistereduser',
            options={'verbose_name': 'usuari no registrat', 'verbose_name_plural': 'usuaris no registrats'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='alumne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contactboard.Alumne'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unregisteredUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanager.UnregisteredUser', verbose_name='usuari (no registrat)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuari'),
        ),
        migrations.AlterField(
            model_name='unregistereduser',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[\\w.@+-]{1,30}$'), usermanager.models.validate_username_unique], verbose_name="nom d'usuari"),
        ),
    ]
