# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumpte', models.CharField(max_length=80)),
                ('tancat', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'conversació',
                'verbose_name_plural': 'conversacions',
            },
        ),
        migrations.CreateModel(
            name='EstatMissatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vist', models.BooleanField(default=False)),
                ('destinatari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrupDeMissatgeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('usuaris', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'grups de missatgeria',
            },
        ),
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(editable=False)),
                ('contingut', models.TextField(help_text='Suporta <a href="/markdown">Markdown</a>')),
                ('enviat', models.DateTimeField(auto_now_add=True)),
                ('editat', models.DateTimeField(auto_now=True)),
                ('conversacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missatges.Conversacio', verbose_name='conversació')),
                ('destinataris', models.ManyToManyField(through='missatges.EstatMissatge', to=settings.AUTH_USER_MODEL)),
                ('per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ha_enviat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estatmissatge',
            name='missatge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missatges.Missatge'),
        ),
        migrations.AddField(
            model_name='conversacio',
            name='a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='missatges.GrupDeMissatgeria'),
        ),
        migrations.AddField(
            model_name='conversacio',
            name='de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='missatge',
            unique_together=set([('conversacio', 'ordre')]),
        ),
    ]
