# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missatges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupdemissatgeria',
            name='motius',
            field=models.TextField(blank=True, help_text='Motius per enviar missatges a aquest grup. Apareixeràn a "Nou missatge". Un per línia.'),
        ),
    ]
