# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missatges', '0002_grupdemissatgeria_motius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missatge',
            options={'ordering': ['-ordre']},
        ),
        migrations.AddField(
            model_name='missatge',
            name='estat',
            field=models.CharField(blank=True, choices=[('CLOSED', 'Tancat'), ('REOPENED', 'Reobert')], max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='estatmissatge',
            unique_together=set([('destinatari', 'missatge')]),
        ),
        migrations.AlterField(
            model_name='missatge',
            name='contingut',
            field=models.TextField(blank=True, help_text='Suporta <a href="/markdown">Markdown</a>'),
        ),
    ]
