# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missatges', '0003_edited_missatges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatmissatge',
            options={'verbose_name': 'estat del missatge', 'verbose_name_plural': 'estat dels missatges'},
        ),
    ]
