# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 18:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import extraescolars.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactboard', '0004_nom_cognoms_pare_mare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraescolar',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('id_interna', models.SlugField(max_length=20, primary_key=True, serialize=False)),
                ('descripcio_curta', models.CharField(blank=True, help_text="Una descripció curta per mostrar a la llista d'extraescolars. Máxim 80 caracters.", max_length=80, verbose_name='Descripció curta')),
                ('descripcio', models.TextField(blank=True, help_text='Suporta <a href="https://ca.wikipedia.org/wiki/Markdown">Markdown</a>', verbose_name='Descripció')),
                ('horari', models.TextField(blank=True, help_text='Suporta <a href="https://ca.wikipedia.org/wiki/Markdown">Markdown</a>')),
                ('inscripcio_des_de', models.DateTimeField(blank=True, help_text="Des de quan es permet la inscripció. No es faràn inscripcions abans d'aquest moment.", null=True, verbose_name='Inscripció des de')),
                ('inscripcio_fins_a', models.DateTimeField(blank=True, help_text="Fins a quan es permet la inscripció. No es faràn inscripcions despés d'aquest moment.", null=True, verbose_name='Inscripció fins a')),
                ('preu', models.DecimalField(blank=True, decimal_places=2, default=extraescolars.models.Extraescolar._preu_default, help_text='Preu en euros. Ha de ser major o igual a 0 i menor que 100', max_digits=4, validators=[django.core.validators.DecimalValidator(4, 2), django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmat', models.BooleanField(default=False, help_text="Si s'ha confirmat (ex. si s'ha enviat la inscripció per correu o si s'ha lliurat a l'AMPA).")),
                ('pagat', models.BooleanField(default=False, help_text="Si està pagat. Si el preu de l'activitat és 0 (gratuït), es marcarà automàticament al guardar.")),
                ('activitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extraescolars.Extraescolar')),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactboard.Alumne')),
            ],
            options={
                'verbose_name_plural': 'inscripcions',
                'verbose_name': 'inscripció',
            },
        ),
        migrations.AddField(
            model_name='extraescolar',
            name='alumnes',
            field=models.ManyToManyField(through='extraescolars.Inscripcio', to='contactboard.Alumne'),
        ),
        migrations.AddField(
            model_name='extraescolar',
            name='cursos',
            field=models.ManyToManyField(blank=True, help_text='Els cursos que es poden inscriure', to='contactboard.Curs'),
        ),
    ]
