# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraescolars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraescolar',
            name='descripcio',
            field=models.TextField(blank=True, help_text='Suporta <a href="/markdown">Markdown</a>', verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='inscripcio',
            name='pagat',
            field=models.BooleanField(default=False, help_text="Si està pagat. Si el preu de l'activitat és 0 (gratuïta), es marcarà automàticament al guardar."),
        ),
    ]
